"""migration third

Revision ID: 70838dfd25f2
Revises: 319c43039c76
Create Date: 2024-04-24 15:50:37.651126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70838dfd25f2'
down_revision = '319c43039c76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ia_friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sex_ia', sa.Enum('Male', 'Female', 'Other', name='sexenumia'), nullable=False),
    sa.Column('age_average', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ia_friends')
    # ### end Alembic commands ###
