"""Initial migration2

Revision ID: 7dfcb629901e
Revises: 
Create Date: 2024-06-25 12:39:47.335587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dfcb629901e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ia_friends', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ia_friends', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
